In [1]:
import numpy as np

In [2]:
A=np.array([[-1, 2],
            [4, 1]])

In [3]:
np.linalg.inv(A)

array([[-0.11111111,  0.22222222],
       [ 0.44444444,  0.11111111]])

In [4]:
A = np.array([[13, 0, 2, 2],
              [3, 4, 1, 4],
              [-1, 0, 1, 5],
              [8, 0, 1, 1]])

In [6]:
np.set_printoptions(suppress=True)

In [8]:
np.linalg.det(A)

48.00000000000001

In [9]:
A = np.array([[12, 0, 12, 4],
              [3, 2, -3, -9],
              [0, 0,  0,  4],
              [-6, 3, -6, -2]])

In [10]:
np.linalg.det(A)

-864.0000000000005

In [11]:
864/48

18.0

In [12]:
C = np.array([
    [1,   0,    2],
    [3,   1,    1],
    [-1,  0,    1]
])

In [13]:
np.linalg.det(C)

3.0000000000000004

In [16]:
(np.linalg.inv(C)*3)

array([[ 1.,  0., -2.],
       [-4.,  3.,  5.],
       [ 1.,  0.,  1.]])

In [17]:
C = np.array([
    [1,   2,  -3],
    [4,   1,   5],
    [6,   7,   1]
])

In [18]:
np.linalg.det(C)

-48.00000000000001

In [22]:
np.linalg.inv(C).dot(C)

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])

In [23]:
A = np.array([
    [2, 1, 3],
    [1,-1, 2],
    [4, 3, 5],
])

In [25]:
np.linalg.inv(A)*2

array([[-11.,   4.,   5.],
       [  3.,  -2.,  -1.],
       [  7.,  -2.,  -3.]])

In [26]:
A = np.array([
    [1,-1, 3],
    [2, 1, 3],
    [3, 4, 2],
])

In [32]:
np.set_printoptions(precision=2)

In [33]:
np.linalg.det(A)

4.8109664400423575e-16

In [37]:
np.linalg.inv(np.array([
    [1, 2, 1],
    [1, 3, 1],
    [0, 2, 1],
]))

array([[ 1.,  0., -1.],
       [-1.,  1.,  0.],
       [ 2., -2.,  1.]])

In [42]:
np.linalg.info.print_function

_Feature((2, 6, 0, 'alpha', 2), (3, 0, 0, 'alpha', 0), 65536)

In [46]:
a = np.array([
    [1, 4, 5, 2],
    [2, 1, 3, 0],
    [-1,3, 2, 2],
])

In [47]:
a[1,:] -= 2*a[0,:]

In [49]:
a[2,:] += a[0,:]

In [51]:
a[2,:] += a[1,:]

In [52]:
a

array([[ 1,  4,  5,  2],
       [ 0, -7, -7, -4],
       [ 0,  0,  0,  0]])

In [76]:
a = np.array([
    [1, 1, -4, -3],
    [2, 0, 2, -2],
    [2, -1, 3, 2],
])

In [77]:
b = np.zeros_like(a)

In [78]:
a

array([[ 1,  1, -4, -3],
       [ 2,  0,  2, -2],
       [ 2, -1,  3,  2]])

In [87]:
for r, x in enumerate([1, 0, -3]):
    b[r, :] = a[r, :] - x*a[1, :]

In [88]:
b

array([[ 1,  0,  1, -1],
       [ 0,  1, -5, -2],
       [ 0,  0, -4,  2]])

In [83]:
a = b.copy()

In [84]:
a[1,:] = a[1,:]/-2

In [86]:
a

array([[ 1,  1, -4, -3],
       [ 0,  1, -5, -2],
       [ 0, -3, 11,  8]])

In [94]:
np.array([
    [-0.6, 0.8, 0.0],
    [0.8,  0.6, 0.0],
    [0, 0, 1],
])*np.array([-7.4, -1.8, 4])

array([[ 4.44, -1.44,  0.  ],
       [-5.92, -1.08,  0.  ],
       [-0.  , -0.  ,  4.  ]])

In [95]:
np.sum(np.array([[ 4.44, -1.44,  0.  ],
       [-5.92, -1.08,  0.  ],
       [-0.  , -0.  ,  4.  ]]), axis=1)

array([ 3., -7.,  4.])

In [96]:
u1, u2 = np.array([0, 1/np.sqrt(5), 2/np.sqrt(5)]), np.array([-5/6, -1/3, 1/6])

In [97]:
u1.dot(u2)

0.0

In [98]:
np.linalg.norm(u1)

0.9999999999999999

In [99]:
np.linalg.norm(u2,)

0.9128709291752769

In [105]:
np.linalg.norm([-1, -0.4, 0.2], ord=2)

1.0954451150103324

In [102]:
6/5

1.2

In [106]:
a = np.eye(3)[:,::-1]

In [107]:
a

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [109]:
v = np.linalg.eig(a)[1]

In [112]:
np.linalg.norm(v, axis=0)

array([1., 1., 1.])